name: "Get traffic"
run-name: "Get traffic : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on:
  push:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  GetTraffic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print date
        run: |
          date
      - name: Npm install
        run: |
          npm install
      - name: Get traffic
        run: |
          npm run startHeadless
