name: "Get traffic"
run-name: "Get traffic : ${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on:
  push:

jobs:
  CreateTag:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      version: "1.0.0"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Npm install
        run: |
          npm install
      - name: Check if version already exist
        id: define_docker_data
        run: |
          npm run start
